// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6R3uDkUDeTmWbqiG1AsrNQc_Uhiv5bFk',
    appId: '1:550480712424:android:1ab80c54a8735c80f1af5d',
    messagingSenderId: '550480712424',
    projectId: 'palm-shop',
    databaseURL: 'https://palm-shop-default-rtdb.firebaseio.com',
    storageBucket: 'palm-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ulqtCx97pgdTk8Zo-bw0wslN7k4oLfw',
    appId: '1:550480712424:ios:596709392805cc8af1af5d',
    messagingSenderId: '606700156156',
    projectId: 'palm-shop',
    databaseURL: 'https://pos-saas-a7b6c-default-rtdb.firebaseio.com',
    storageBucket: 'pos-saas-a7b6c.appspot.com',
    iosBundleId: 'com.TechFaculty.PalmShop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEIbqOglbL5z5fO5_2MUD2XbbEmyYC-rU',
    appId: '1:550480712424:web:1b10c88ef908b337f1af5d',
    messagingSenderId: '550480712424',
    projectId: 'palm-shop',
    authDomain: 'palm-shop.firebaseapp.com',
    databaseURL: 'https://palm-shop-default-rtdb.firebaseio.com',
    storageBucket: 'palm-shop.firebasestorage.app',
    measurementId: 'G-E556GK66FG',
  );

}